# The system prompt used for generating the system role message.
SYSTEM_MESSAGE = """A conversation between a user and a helpful assistant. You are a helpful classification assistant. Respond with ONLY with the final category label."""

# Path to the large source JSON dataset (array of objects with 'category' and 'content')
INPUT_JSON_PATH = "./_inputs/structured_messages.json"

# Primary + additional eval JSONL output paths.
# The first path in the list is treated as the canonical eval output produced
# directly by sample_data.py; the remaining paths will be populated by copying
# that file after generation (see tasks.py / sample_data task).
EVAL_JSONL_PATHS = [
    "./_outputs/data/structured_messages_eval.jsonl",
    "../../PublicHTTP/api/v26_0_0/_autogenerated/structuredmessageeval.jsonl",
]

# Train JSONL output path
TRAIN_JSONL_PATH = "_outputs/data/structured_messages_train.jsonl"

# ------------------------------------------------------------------
# Additional constants for training / generation / export workflows
# (Added on top of the provided base)
# ------------------------------------------------------------------

# Default learning rate for training tasks (epochs & batch size are CLI args)
LEARNING_RATE = 1e-3

# Base directory where per-run checkpoint subdirectories (named by --name) live
CHECKPOINTS_BASE_DIR = "_outputs/checkpoints"

# Base directory for export artifacts (one subdirectory per --name)
EXPORTS_BASE_DIR = "_outputs/exports"

MAX_ENTRIES_PER_FILE = 1000

__all__ = [
    "SYSTEM_MESSAGE",
    "INPUT_JSON_PATH",
    "TRAIN_JSONL_PATH",
    "EVAL_JSONL_PATHS",
    "LEARNING_RATE",
    "CHECKPOINTS_BASE_DIR",
    "EXPORTS_BASE_DIR",
    "MAX_ENTRIES_PER_FILE"
]
